(wip) Fumo item
Alexejhero/Neurosama-Subnautica-Mod pull request #29
Opened 2023-10-03 13:08 UTC by Govorunb

Fixes the game-breaking issue where you couldn't hold and hug the fumo
I also applied transforms on the fbx because it was bothering me
(draft while I struggle against the IK system)

2023-11-02 17:55 UTC, Alexejhero requested changes

2023-11-02 17:55 UTC, Alexejhero commented on Unity/Assets/Scripts/SCHIZO/Items/FumoItem/FumoItemLoader.cs
> +#endif
move to actual ItemData class pls

2023-11-02 17:55 UTC, Alexejhero commented on SCHIZO/Items/Gymbag/GymbagLoader.cs
> +        new Gymbag(itemData.ModItem, ((CloneItemData)itemData).CloneTarget).Register();
blabbering

2023-11-02 17:55 UTC, Alexejhero commented on SCHIZO/Items/FumoItem/FumoItemLoader.cs
> +        // TODO: move to a "coordinated spawns" scriptable object?
yes

2023-11-02 17:55 UTC, Alexejhero commented on SCHIZO/Items/FumoItem/FumoItem.cs
> +}
move to unity

2023-11-02 18:23 UTC, Govorunb commented
i've added project items based on the comments 👍

2023-11-06 18:40 UTC, Alexejhero approved these changes

2023-11-06 18:41 UTC, merged