Move sounds to FMOD
Alexejhero/Neurosama-Subnautica-Mod pull request #56
Opened 2023-12-16 05:35 UTC by Govorunb

This will:
- Reduce Unity asset build times by a bunch (FMOD Studio actually does builds correctly btw)
- Obsolete FMODSoundCollection (sad, I know) which is one fewer workaround we have to maintain
- Reduce total asset sizes by 5-10% since we can remove duplicate sounds + FMOD builds are just better

Come to the FMOD side, we have parameters, effects, mixing, and ---> *hot reload* <---
I fixed an issue entirely in FMOD Studio, pressed F7, and tested the fix without having to restart Subnautica. it's so good

2023-12-18 01:21 UTC, Alexejhero commented
what am i even supposed to review here

2023-12-18 04:29 UTC, Govorunb commented
yeah it's a bit much sorry
it should only show the actually relevant changes if you [skip the first commit](https://github.com/Alexejhero/Neurosama-Subnautica-Mod/pull/56/files/2a8c34be2f818c59ddfa8e4ac54d2740037933c7..bab5847f68615ff914f87c40cc642681718a6d12) and deselect `xml` and `meta` from the file filter

2023-12-19 22:54 UTC, Govorunb commented
do you care if i just merge this? i've tested the sounds pretty extensively

i mean just look at this isn't it tantalising
![image](https://github.com/Alexejhero/Neurosama-Subnautica-Mod/assets/3830522/9277fe60-43c5-468b-9132-e46359337788)

2023-12-20 21:02 UTC, Alexejhero requested changes

2023-12-20 21:02 UTC, Alexejhero commented on .gitattributes
> +FMOD Project/**/*.xml text eol=lf
this doesnt work

2023-12-20 21:56 UTC, Alexejhero approved these changes

2023-12-21 02:00 UTC, merged